[versions]
versionName = "3.0.0"
android-versionCode = "58"

filekitCompose = "0.8.7"
inAppReview = "3.1.21"
korgeCore = "5.1.0"
multiplatformSettings = "1.2.0"
permissions = "0.18.1"

agp = "8.5.2"
coreGoogleShortcuts = "1.1.0"
coreSplashscreen = "1.2.0-alpha02"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.2"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.6.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
coil = "3.0.0-alpha06"
#compose-plugin = "1.7.0-alpha02"
compose-plugin = "1.7.0-beta01" # Beta-02 contains bug with frame on iphone 13 mini
credentials = "1.3.0-rc01"
deeplink = "2.1.1"
googleid = "1.1.1"
imageLoader = "1.8.2"
junit = "4.13.2"
kotlin = "2.0.20"
kotlinxDatetime = "0.6.1"
ktor = "3.0.0-beta-2"
ktor-client = "3.0.0-beta-2"
ktorClientWasm = "3.0.0-beta-2"
logback = "1.5.6"
ksp-google = "2.0.20-1.0.25"
# ksp-google = "1.9.24-1.0.20"
ktlint = "12.1.1"
images-kamael = "0.9.5"
coroutinesVersion = "1.9.0-RC.2"
kotlinx-io = "0.5.1"
firebase = "2.1.0"
gservice = "4.4.2"
kermit = "2.0.4"
crashlytics = "3.0.2"
dokka = "1.9.20"
kotest = "5.5.4"
billing-android = "7.1.1"

# wasmJs support
koin = "4.0.0-RC1"
koin-ksp = "1.4.0-RC3"
material3WindowSizeClassMultiplatform = "0.5.0"
#navigationCompose = "2.8.0-alpha08"
navigationCompose = "2.7.0-alpha07"

cupertino = "0.1.0-alpha04"
materialKolor = "1.7.0"

[libraries]
androidx-core-google-shortcuts = { module = "androidx.core:core-google-shortcuts", version.ref = "coreGoogleShortcuts" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
deeplink = { module = "com.motorro.keeplink:deeplink", version.ref = "deeplink" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
korge-core = { module = "com.soywiz.korge:korge-core", version.ref = "korgeCore" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissions" }
review = { module = "io.github.sergeimikhailovskii:in-app-review-kmp", version.ref = "inAppReview" }
review-gplay = { module = "io.github.sergeimikhailovskii:in-app-review-kmp-google-play", version.ref = "inAppReview" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutinesVersion" }
kotlinx-coroutines-wasmjs = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-wasm-js", version.ref = "coroutinesVersion" }
kotlinx-coroutines-js = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-js", version.ref = "coroutinesVersion" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesVersion"}
kotlinx-io = { group = "org.jetbrains.kotlinx", name ="kotlinx-io-core", version.ref = "kotlinx-io" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-tests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor" }


ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor-client" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorClientWasm" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-js = { group = "io.insert-koin", name = "koin-core-js", version.ref = "koin" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }

window-multiplatform = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "material3WindowSizeClassMultiplatform" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

firebase-common-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
firebase-common-functions = { module = "dev.gitlive:firebase-functions", version.ref = "firebase" }
firebase-common-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebase-common-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
firebase-common-perf = { module = "dev.gitlive:firebase-perf", version.ref = "firebase" }
firebase-common-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "firebase" }
firebase-common-installations = { module = "dev.gitlive:firebase-installations", version.ref = "firebase" }
firebase-common-storage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase" }
firebase-common-messaging = { module = "dev.gitlive:firebase-messaging", version.ref = "firebase" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

cupertino-core = { module = "io.github.alexzhirkevich:cupertino", version.ref = "cupertino" }
cupertino-native = { module = "io.github.alexzhirkevich:cupertino-native", version.ref = "cupertino" }
cupertino-adaptive = { module = "io.github.alexzhirkevich:cupertino-adaptive", version.ref = "cupertino" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }

billing-android = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing-android" }

[bundles]
ktor-common = ["ktor-client-core", "ktor-client-json", "ktor-client-logging", "ktor-client-serialization", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]
cupertino = ["cupertino-core", "cupertino-native", "cupertino-adaptive"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-google" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version.ref = "gservice" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

